version: "3"
services:
    app:
      image: node:lts-bullseye
      tty: true
      restart: unless-stopped
      working_dir: /usr/src/app
      ports:
        - "5173:5173"
      volumes:
        - ./:/usr/src/app